 var pop1 = function(){
   var appear1 = document.getElementById("popbc");
   appear1.style.display = "inline";
   var appear2 = document.getElementById("pop1");
   appear2.style.display = "inline";}
var pop2 = function(){
   var appear1 = document.getElementById("popbc");
   appear1.style.display = "inline";
   var appear2 = document.getElementById("pop2");
   appear2.style.display = "inline";}
var pop3 = function(){
   var appear1 = document.getElementById("popbc");
   appear1.style.display = "inline";
   var appear2 = document.getElementById("pop3");
   appear2.style.display = "inline";}
var popout = function(){
   var appear1 = document.getElementById("popbc");
   appear1.style.display = "none";
   var appear2 = document.getElementById("pop1");
   appear2.style.display = "none";
   var appear3 = document.getElementById("pop2");
   appear3.style.display = "none";
   var appear4 = document.getElementById("pop3");
   appear4.style.display = "none";}
